const express = require("express");
const { stationRouter } = require("../router/station.router");
const { userRouter } = require("./user.router");
const { TripRouter } = require("../router/trip.router");
const { postsRouter } = require("../router/posts.router");
const { ticketRouter } = require("../router/ticket.router");
const { reviewsation } = require("../router/reviewsation.router");
const rootRouter = express.Router();
rootRouter.use("/stations", stationRouter);
rootRouter.use("/user", userRouter);
rootRouter.use("/trip", TripRouter);
rootRouter.use("/posts", postsRouter);
rootRouter.use("/ticket", ticketRouter);
rootRouter.use("/review", reviewsation);
module.exports = { rootRouter };
